### ISSUE TITLE
persistent meteortoys_toykit Property 'undefined'

### ISSUE THREAD

**Issue by peonmodel** [MeteorToys/allthings#39]
Thanks for the great tool

Currently i have a problem that meteortoys persistently crashes with the error shown below
it was working with Meteor 1.2.0.2 and allthings v2 just fine the day before

i have tried reinstalling meteor, downgrading allthings to v1.2.3 (the previous working version i had) and checked out my code from 2 days before, none of it works

my teammates have no issues

removing meteortoys will avoid the crash but i dont really want to work without the useful tool

please advise

```
TypeError: Property 'undefined' of object [object Object] is not a function
     at Package (meteor://💻app/packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
    at Package (meteor://💻app/packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
     at /Users/local/Documents/repos/dvmp/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
    at /Users/local/Documents/repos/dvmp/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
     at /Users/local/Documents/repos/dvmp/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
     at Function._.each._.forEach (/Users/local/.meteor/packages/meteor-tool/.1.1.9.1sd3e7j++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/local/Documents/repos/dvmp/.meteor/local/build/programs/server/boot.js:137:5
```

if it helps, this is the list of packages i had

```
accounts-base@1.2.1
accounts-password@1.1.3
aldeed:simple-schema@1.3.3
amplify@1.0.0
anti:fake@0.4.1
arillo:flow-router-helpers@0.4.5
audit-argument-checks@1.0.4
autoupdate@1.2.3
babel-compiler@5.8.24_1
babel-runtime@0.1.4
base64@1.0.4
binary-heap@1.0.4
blaze@2.1.3
blaze-html-templates@1.0.1
blaze-tools@1.0.4
boilerplate-generator@1.0.4
caching-compiler@1.0.0
caching-html-compiler@1.0.2
callback-hook@1.0.4
ccorcos:subs-cache@0.0.5
check@1.0.6
coffeescript@1.0.10
cosmos:browserify@0.5.1
dburles:mongo-collection-instances@0.3.4
ddp@1.2.2
ddp-client@1.2.1
ddp-common@1.2.1
ddp-rate-limiter@1.0.0
ddp-server@1.2.1
deps@1.0.9
diff-sequence@1.0.1
ecmascript@0.1.5
ecmascript-collections@0.1.6
edgee:slingshot@0.7.1
ejson@1.0.7
email@1.0.7
fastclick@1.0.7
flemay:less-autoprefixer@1.1.0
force-ssl@1.0.6
geojson-utils@1.0.4
gfk:mailgun-api@1.1.0
gwendall:body-events@0.1.6
hot-code-push@1.0.0
html-tools@1.0.5
htmljs@1.0.5
http@1.1.1
id-map@1.0.4
jparker:crypto-core@0.1.0
jparker:crypto-md5@0.1.1
jparker:crypto-sha1@0.1.0
jparker:crypto-sha256@0.1.1
jquery@1.11.4
juliancwirko:s-alert@3.1.0
juliancwirko:s-alert-stackslide@3.1.0
kadira:blaze-layout@2.1.0
kadira:flow-router@2.6.2
lai:collection-extensions@0.1.4
launch-screen@1.0.4
less@2.5.0_3
livedata@1.0.15
localstorage@1.0.5
logging@1.0.8
manuel:isdev@1.0.0
manuel:reactivearray@1.0.5
manuel:viewmodel@1.9.12
manuel:viewmodel-explorer@1.0.5
markdown@1.0.5
meteor@1.1.9
meteor-base@1.0.1
meteorhacks:aggregate@1.3.0
meteorhacks:async@1.0.0
meteorhacks:collection-utils@1.2.0
meteorhacks:kadira@2.23.4
meteorhacks:kadira-binary-deps@1.4.0
meteorhacks:kadira-profiler@1.2.0
meteorhacks:meteorx@1.3.1
meteorhacks:npm@1.5.0
meteorhacks:unblock@1.1.0
meteortoys:allthings@2.0.0
meteortoys:authenticate@1.0.0
meteortoys:autopub@1.0.0
meteortoys:blueprint@1.0.0
meteortoys:email@1.0.0
meteortoys:hotreload@1.0.0
meteortoys:listen@1.0.0
meteortoys:method@1.0.0
meteortoys:pro@1.0.0
meteortoys:pub@1.0.0
meteortoys:result@1.0.0
meteortoys:shell@1.0.0
meteortoys:status@1.0.0
meteortoys:sub@1.0.0
meteortoys:throttle@1.0.0
meteortoys:toykit@1.0.0
meteortoys:toypro@1.0.0
minifiers@1.1.7
minimongo@1.0.10
mobile-experience@1.0.1
mobile-status-bar@1.0.6
momentjs:moment@2.10.6
mongo@1.1.2
mongo-id@1.0.1
mongo-livedata@1.0.9
msavin:jetsetter@1.1.0
msavin:mongol@1.2.0
npm-bcrypt@0.7.8_2
npm-container@1.2.0
npm-mongo@1.4.39_1
observe-sequence@1.0.7
ordered-dict@1.0.4
package-version-parser@3.0.4
peerlibrary:aws-sdk@2.1.47_1
peerlibrary:blocking@0.5.2
percolate:synced-cron@1.3.0
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
promise@0.5.0
ramda:ramda@0.17.1
random@1.0.4
rate-limit@1.0.0
reactive-dict@1.1.2
reactive-var@1.0.6
reload@1.1.4
retry@1.0.4
reywood:publish-composite@1.4.2
routepolicy@1.0.6
sacha:spin@2.3.1
sanjo:jasmine@0.20.0
sanjo:karma@3.0.2
sanjo:long-running-child-process@1.1.3
sanjo:meteor-files-helpers@1.2.0_1
sanjo:meteor-version@1.0.0
semantic:ui@2.1.4
semantic:ui-data@2.1.4
service-configuration@1.0.5
session@1.1.1
sha@1.0.4
simple:json-routes@1.0.4
spacebars@1.0.7
spacebars-compiler@1.0.7
srp@1.0.4
standard-minifiers@1.0.1
templating@1.1.4
templating-tools@1.0.0
tinytest@1.0.6
tracker@1.0.9
ui@1.0.8
underscore@1.0.4
url@1.0.5
validatis:file-model@0.0.1
validatis:toolbox@0.0.1
velocity:chokidar@1.0.3_1
velocity:console-reporter@0.1.3
velocity:core@0.10.0
velocity:html-reporter@0.9.0
velocity:meteor-internals@1.1.0_7
velocity:meteor-stubs@1.1.0
velocity:shim@0.1.0
velocity:source-map-support@0.3.2_1
webapp@1.2.2
webapp-hashing@1.0.5
xolvio:cucumber@0.14.1
zimme:active-route@2.3.2

```

**Comment by 6uimorais** [comment]
This is happening to me too, when I try to start a new project , add "meteortoys:allthings"  and try to run the project, I get the exactly same error. I tried to reinstall meteor and cleaning everything, but did not solve the problem. 
(Ubuntu 14.04 LTS, Node v0.12.1, Meteor 1.2.0.2)

**Comment by merlinstardust** [comment]
I was just about to post this issue. My upgrade to Toys 2.0 was working fine until about an hour ago when it started crashing. At first I thought it was my code changes, but I reverted and still got them. The only way I fixed it was to remove Toys, which is obviously not what I want to do.

**Comment by thebarty** [comment]
Hi guys,

just ran into a similar error. This is a excerp of the trace:

```
/packages/meteor-tool/.1.1.9.y1t50u++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150930-09:04:48.861(2)? (STDERR)                         throw(ex);
W20150930-09:04:48.861(2)? (STDERR)                               ^
W20150930-09:04:48.864(2)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-09:04:48.864(2)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-09:04:48.864(2)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
```

It disappeard after removing meteortoys.

**Comment by Anima-t3d** [comment]
I ran into the same issue, although it worked fine for hours before that point. It just seem to occur at random after a save (which triggers the build), each individual build goes fine until it all has to be build into a final application build...

**Comment by skeltoras** [comment]
+1, same by my apps. The day before all is working and today i've got this same error print.

**Comment by msavin** [comment]
Hey everyone, sorry about the issue! It was working when I did the first run.. but now I am experiencing it too. Just out of curiosity, is anyone having this issue with Meteor 1.1?

**Comment by jamiewilson** [comment]
I just upgraded to 1.2 this morning and encountered this issue. It was not a problem on 1.1, afaik.

**Comment by vieko** [comment]
+1 on this issue... I upgraded to Meteor 1.2 yesterday, it was working fine. When I started the project today, this problem reared its ugly head :)

**Comment by 0xpatrickdev** [comment]
+1 ... had it working yesterday with 1.2, just ran into the issue late last night / today

**Comment by iamjaredwalters** [comment]
+1, same boat as pcooney10, was working fine with 1.2 yesterday and became an issue sometime in the evening

**Comment by msavin** [comment]
I just pushed up an update.. I have no idea what broke but it looks like its working now. Can you guys please confirm? 

I am testing on todos app with Meteor 1.2

**Comment by iamjaredwalters** [comment]
@msavin, so far so good :)

**Comment by merlinstardust** [comment]
Same here. Thanks for the quick fix!

**Comment by msavin** [comment]
Awesome, thanks guys!

**Comment by Anima-t3d** [comment]
Directly after the update I got this: https://github.com/MeteorToys/allthings/issues/40
